/**
 * Pure, dependency-free core for caption generation across providers.
 *
 * Captions can be generated by either Grok (xAI, OpenAI-compatible API) or
 * Claude (Anthropic). The provider is selected at runtime via the
 * CAPTION_PROVIDER env var so we can flip back to Claude instantly if Grok
 * output disappoints — no code change / redeploy needed.
 *
 * Everything here is a pure function (no network, no SDK) so it's unit-testable
 * without mocks. The actual HTTP/SDK calls live in caption-llm.ts.
 */

export type CaptionProvider = 'grok' | 'claude'

/** Default Grok model for captions: fast + cheap, plenty for short copy. */
export const GROK_CAPTION_MODEL = 'grok-4-1-fast-non-reasoning'
/** Claude caption model (fallback provider). */
export const CLAUDE_CAPTION_MODEL = 'claude-sonnet-4-6'
/** xAI's OpenAI-compatible chat-completions endpoint. */
export const GROK_CHAT_COMPLETIONS_URL = 'https://api.x.ai/v1/chat/completions'

/** Env we read — kept narrow so tests can pass plain objects. */
export interface CaptionEnv {
  CAPTION_PROVIDER?: string
  XAI_API_KEY?: string
  ANTHROPIC_API_KEY?: string
  /** Optional override of the Grok model id without a code change. */
  GROK_CAPTION_MODEL?: string
  // Index signature so NodeJS's ProcessEnv is assignable here.
  [key: string]: string | undefined
}

/**
 * Resolve which provider to use. Defaults to Grok. Accepts a few friendly
 * aliases; anything unrecognized falls back to Grok (the intended default).
 */
export function resolveCaptionProvider(env: CaptionEnv): CaptionProvider {
  const raw = (env.CAPTION_PROVIDER ?? '').trim().toLowerCase()
  if (raw === 'claude' || raw === 'anthropic') return 'claude'
  return 'grok'
}

/** The model id for the resolved provider (also recorded in saved_captions). */
export function captionModelId(env: CaptionEnv): string {
  if (resolveCaptionProvider(env) === 'claude') return CLAUDE_CAPTION_MODEL
  return (env.GROK_CAPTION_MODEL ?? '').trim() || GROK_CAPTION_MODEL
}

/** Env var name that must be set for the resolved provider. */
export function requiredKeyName(env: CaptionEnv): 'XAI_API_KEY' | 'ANTHROPIC_API_KEY' {
  return resolveCaptionProvider(env) === 'claude' ? 'ANTHROPIC_API_KEY' : 'XAI_API_KEY'
}

/**
 * Returns a Spanish error message if the resolved provider's API key is missing,
 * otherwise null. Lets call sites fail fast before doing DB work.
 */
export function captionConfigError(env: CaptionEnv): string | null {
  const provider = resolveCaptionProvider(env)
  const key = provider === 'claude' ? env.ANTHROPIC_API_KEY : env.XAI_API_KEY
  if (key && key.trim().length > 0) return null
  return `${requiredKeyName(env)} no está configurado en el servidor.`
}

export interface GrokRequest {
  url: string
  headers: Record<string, string>
  body: string
}

/** Build the OpenAI-compatible Grok chat-completions request. */
export function buildGrokRequest(input: {
  prompt: string
  apiKey: string
  model: string
  maxTokens: number
}): GrokRequest {
  return {
    url: GROK_CHAT_COMPLETIONS_URL,
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${input.apiKey}`,
    },
    body: JSON.stringify({
      model: input.model,
      max_tokens: input.maxTokens,
      messages: [{ role: 'user', content: input.prompt }],
    }),
  }
}

/** Extract the caption text from a Grok (OpenAI-shaped) response. */
export function parseGrokResponse(json: unknown): string {
  const choices = (json as { choices?: { message?: { content?: unknown } }[] })?.choices
  const content = choices?.[0]?.message?.content
  return typeof content === 'string' ? content.trim() : ''
}

/** Extract the caption text from Claude's content-block array. */
export function parseClaudeContent(
  blocks: { type?: string; text?: string }[] | undefined,
): string {
  if (!Array.isArray(blocks)) return ''
  return blocks
    .filter((b) => b?.type === 'text' && typeof b.text === 'string')
    .map((b) => b.text as string)
    .join('')
    .trim()
}
