from pathlib import Path
import json,html,subprocess
R=Path(__file__).resolve().parent;out=R/'runs'
items=json.load(open(R/'runs/catalog-reedit-items.json'))
catalog=json.load(open(out/'catalog.json'));cards=[];manifest=[]
for slug,version,title in items:
 name=f'nanas-{slug}-v{version}';video=out/(name+'.mp4')
 if not video.exists():raise RuntimeError('Missing '+name)
 report=json.load(open(out/(name+'.json')));idea=next(i for i in catalog['ideas'] if i['id']==report['edit']['idea_id'])
 duration=report['verification']['duration'];poster=name+'-poster.jpg'
 subprocess.run(['ffmpeg','-v','error','-ss','0.7','-i',str(video),'-frames:v','1','-vf','scale=360:640','-y',str(out/poster)],check=True)
 cards.append(f'''<article id="{slug}"><div class="media"><video controls playsinline preload="none" poster="{poster}" src="{name}.mp4"></video></div><div class="copy"><p class="eyebrow">NANA’S PLAYHOUSE · {duration:.1f} s</p><h2>{html.escape(title)}</h2><p class="status">Listo Para Tu Revisión</p><a class="download" href="{name}.mp4" download>Descargar MP4 ↓</a><details><summary>Idea Y Revisión</summary><p><strong>{html.escape(idea['title'])}</strong></p><p>{html.escape(idea['hook'] or '')}</p><p>Fuente QUARTZO. Música: {html.escape(report["edit"]["music"]["title"])} (CC0). Ambiente reducido y outro oficial. Revisión visual realizada; escucha y aprobación final pendientes.</p><a href="{name}-compare.jpg">Ver Fotogramas</a> · <a href="{name}.review.json">Registro De Revisión</a></details></div></article>''')
 manifest.append({'title':title,'idea_id':idea['id'],'video':name+'.mp4','duration':duration,'status':'local_review','version':version})
(out/'nanas-batch-manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2))
page='''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nana’s Playhouse · Nuevos Reels</title><style>*{box-sizing:border-box}body{margin:0;background:#fff9fb;color:#271b2b;font:16px/1.5 system-ui,sans-serif}header{max-width:1160px;margin:auto;padding:48px 24px 28px}.eyebrow{color:#ad0079;font-size:12px;letter-spacing:.08em;font-weight:800}h1{font-size:clamp(32px,5vw,54px);line-height:1.05;margin:12px 0}header p{max-width:670px;color:#675b68}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px;max-width:1160px;margin:0 auto;padding:0 24px 48px}article{background:white;border:1px solid #ecdce8;border-radius:20px;overflow:hidden;display:grid;grid-template-columns:minmax(0,45%) minmax(0,55%)}video{display:block;width:100%;aspect-ratio:9/16;background:#201921}.copy{padding:22px;min-width:0}h2{font-size:23px;line-height:1.15;margin:12px 0 20px}.status{font-size:13px;color:#62566a}.download{display:inline-block;padding:11px 14px;border-radius:9px;background:#b90085;color:white;text-decoration:none;font-size:14px;font-weight:700}details{margin-top:24px;font-size:13px;color:#6c5f6c}summary{cursor:pointer;font-weight:600}a{color:#a50076}footer{max-width:1160px;margin:auto;padding:0 24px 36px;color:#6c5f6c;font-size:13px}@media(max-width:850px){.grid{grid-template-columns:1fr}}@media(max-width:430px){article{grid-template-columns:1fr}.media{max-width:280px;width:100%;margin:auto}.copy{padding:20px}h2{font-size:24px}}</style></head><body><header><div class="eyebrow">NATE MEDIA / EDICIÓN</div><h1>Más Ideas.<br>Más Momentos En Nana’s.</h1><p>Ocho nuevos reels a partir de las ideas y grabaciones del dashboard. Elige un video para revisarlo o descargarlo.</p><p><a href="broll-catalog/index.html">Explorar Biblioteca De 35 B-roll →</a> · <a href="effects/index.html">Laboratorio De Efectos →</a></p></header><main class="grid">'''+''.join(cards)+'''</main><footer>Ediciones locales, sin publicar. <a href="review.html">Pregunta</a> · <a href="clima.html">Clima</a> · <a href="tour.html">Tour</a><p>La licencia comercial de la fuente QUARTZO suministrada sigue pendiente de verificar.</p></footer><script>document.querySelectorAll('video').forEach(v=>v.addEventListener('play',()=>document.querySelectorAll('video').forEach(o=>{if(o!==v)o.pause()})));</script></body></html>'''
(out/'nanas.html').write_text(page)
print('Review gallery: /nanas.html')
