import {beforeEach,it,expect,vi} from 'vitest'
const h=vi.hoisted(()=>({idea:{} as any,historyFail:false,fileDate:'2026-09-08T12:00:00Z',writes:[] as any[],history:[] as any[]}))
vi.mock('@/lib/auth/server',()=>({requirePermission:async()=>{},currentUserHas:async()=>false}))
vi.mock('next/cache',()=>({revalidatePath:vi.fn()}))
vi.mock('@/lib/supabase/server',()=>({createClient:async()=>({auth:{getUser:async()=>({data:{user:{id:'reviewer'}}})},from:(table:string)=>{const q:any={select:()=>q,eq:()=>q,in:()=>q,not:()=>q,is:()=>q,order:()=>q,limit:()=>q,single:async()=>({data:h.idea,error:null}),maybeSingle:async()=>({data:table==='content_idea_videos'?{id:'f'}:h.idea,error:null}),insert:async(p:any)=>{h.history.push(p);return {error:h.historyFail?{message:'fail'}:null}},update:(p:any)=>{h.writes.push(p);return q},then:(r:any)=>r({data:table==='content_idea_videos'?[{id:'f',uploaded_at:h.fileDate}]:table==='content_idea_activity'?[{created_at:'2026-09-08T11:00:00Z'}]:[h.idea],error:null})};return q}})}))
import {decideReview,resubmitForReview} from './pipeline-submit'
beforeEach(()=>{h.idea={id:'i',created_by:'editor',approval_status:'submitted',client:{assigned_to:'reviewer'}};h.writes=[];h.history=[];h.historyFail=false;h.fileDate='2026-09-08T12:00:00Z'})
it('seals the exact reviewed file and records subtitle verification',async()=>{expect(await decideReview({ideaId:'i',decision:'approve',videoFileId:'f',captionsVerified:true,videoVerified:true})).toMatchObject({ok:true});expect(h.writes[0]).toMatchObject({approved_video_id:'f',approval_status:'approved'});expect(h.history[0].metadata.captionsVerified).toBe(true)})
it('does not change status when the correction note cannot be saved',async()=>{h.historyFail=true;expect(await decideReview({ideaId:'i',decision:'request_changes',note:'Corrige 00:12'})).toHaveProperty('error');expect(h.writes).toEqual([])})
it('returns corrections with the note and clears the approved file',async()=>{await decideReview({ideaId:'i',decision:'request_changes',note:'Corrige 00:12'});expect(h.history[0].metadata.note).toBe('Corrige 00:12');expect(h.writes[0]).toMatchObject({approval_status:'revision_needed',approved_video_id:null})})
it('rejects resubmitting the old file and preserves the publication date',async()=>{h.idea.approval_status='revision_needed';h.fileDate='2026-09-08T10:00:00Z';expect(await resubmitForReview('i')).toHaveProperty('error');expect(h.writes).toEqual([]);h.fileDate='2026-09-08T12:00:00Z';expect(await resubmitForReview('i')).toMatchObject({ok:true});expect(h.writes[0]).not.toHaveProperty('publish_date')})

it('allows the task editor when the client has another editor',async()=>{h.idea.approval_status='revision_needed';h.idea.client={assigned_to:'another-editor'};h.idea.production_task={assigned_to_id:'reviewer'};expect(await resubmitForReview('i')).toMatchObject({ok:true})})
