'use client'
import { useState } from 'react'
import { reconcileTodayChecklist } from '@/lib/utils/reconcile-today-checklist'
import type { OperationalPublicationReport } from '@/lib/utils/operational-publications'
import { WorkflowRefresh } from './workflow-refresh'
import { ReopenReviewButton } from '@/components/review/reopen-review-button'
import { PublishToMetricoolButton } from '@/components/produccion/publish-metricool-button'
import { PublicationChecklist } from './publication-checklist'
import Link from 'next/link'
import { ArrowUpRight, CheckCircle2, Circle, CalendarDays, Film, ClipboardCheck, Send } from 'lucide-react'
import type { OperationsOverview, OverviewItem } from '@/lib/utils/operations-overview'

function TaskRow({item}:{item:OverviewItem}){
 return <li className="rounded-xl border bg-background p-4">
  <div className="flex flex-wrap items-start justify-between gap-3">
   <div className="min-w-0 flex-1"><p className="text-xs font-medium text-muted-foreground">{item.client} · {item.owner}</p><Link href={item.href} className="mt-1 block break-words text-sm font-semibold hover:underline">{item.title}</Link></div>
   <span className={`max-w-full rounded-md px-2 py-1 text-xs ${item.done?'bg-green-500/10 text-green-600 dark:text-green-400':'bg-amber-500/10 text-amber-700 dark:text-amber-400'}`}>{item.state}</span>
  </div>
  {item.state==='Listo Para Agendar'&&<div className="mt-3"><PublishToMetricoolButton ideaId={item.id}/></div>}
  {item.state==='Verificar Video Y Subtítulos'&&<ReopenReviewButton ideaId={item.id}/>}
  {item.checks.length>0&&<ul aria-label="Checklist Del Video" className="mt-3 flex flex-wrap gap-x-4 gap-y-2">{item.checks.map(c=><li key={c.label} className={`flex items-center gap-1.5 text-[11px] ${c.done?'text-green-600 dark:text-green-400':'text-muted-foreground'}`}>{c.done?<CheckCircle2 aria-label="Completado" className="h-3.5 w-3.5"/>:<Circle aria-label="Pendiente" className="h-3.5 w-3.5"/>}{c.label}</li>)}</ul>}
 </li>
}
function Queue({id,title,items,href,empty}:{id:string;title:string;items:OverviewItem[];href:string;empty:string}){
 return <section id={id} className="min-w-0 scroll-mt-24 rounded-xl border bg-card p-4 sm:p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">{title} <span className="text-muted-foreground">({items.length})</span></h2><Link href={href} className="inline-flex min-h-11 items-center gap-2 text-xs font-medium text-primary">Abrir Tablero <ArrowUpRight className="h-4 w-4"/></Link></div>{items.length?<><ul className="space-y-2">{items.slice(0,5).map(i=><TaskRow key={i.id} item={i}/>)}</ul>{items.length>5&&<details className="mt-3"><summary className="cursor-pointer py-3 text-sm text-primary">Ver {items.length-5} Más</summary><ul className="space-y-2">{items.slice(5).map(i=><TaskRow key={i.id} item={i}/>)}</ul></details>}</>:<p className="py-4 text-sm text-muted-foreground">{empty}</p>}</section>
}
export function OperationsOverviewView({data:source}:{data:OperationsOverview}){
 const [report,setReport]=useState<OperationalPublicationReport|null>(null)
 const data={...source,today:reconcileTodayChecklist(source.today,source.date,report)}
 const pending=data.today.filter(i=>!i.done).length
 const free=data.editors.reduce((n,e)=>n+e.free,0)
 const cards=[{label:'Por Publicar Hoy',count:pending,note:`${data.today.length} compromisos de hoy`,icon:CalendarDays,href:'#hoy'},{label:'Espacios Por Llenar',count:free,note:`${data.editors.filter(e=>e.free).length} editores con espacio`,icon:Film,href:'#editores'},{label:'Revisiones Pendientes',count:data.reviews.length,note:`${data.corrections.length} videos en corrección`,icon:ClipboardCheck,href:'#revisiones'},{label:'Listos Para Agendar',count:data.ready.length,note:'Aprobados, con copy y fecha válida',icon:Send,href:'#agendar'}]
 return <div className="mx-auto max-w-7xl space-y-6 pb-8"><WorkflowRefresh />
  <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-widest text-primary">Resumen Operativo · Equipo</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Mi Día</h1><p className="mt-2 text-sm text-muted-foreground">{new Date(data.date+'T12:00:00Z').toLocaleDateString('es-PR',{weekday:'long',day:'numeric',month:'long',timeZone:'America/Puerto_Rico'})} · Hora de Puerto Rico</p></div><Link href="/published" className="inline-flex min-h-11 items-center gap-2 rounded-lg border px-4 text-sm font-medium">Verificar En Metricool <ArrowUpRight className="h-4 w-4"/></Link></header>
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(c=><a key={c.label} href={c.href} className="min-w-0 rounded-xl border bg-card p-4 transition hover:border-primary/60 sm:p-5"><c.icon className="mb-4 h-5 w-5 text-primary"/><p className="text-3xl font-semibold tabular-nums">{c.count}</p><p className="mt-1 text-sm font-semibold">{c.label}</p><p className="mt-2 text-xs text-muted-foreground">{c.note}</p></a>)}</div>
  <PublicationChecklist onReport={setReport} />
  <section id="hoy" className="scroll-mt-24 rounded-xl border bg-card p-4 sm:p-5"><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Checklist De Hoy</h2><p className="mt-1 text-xs text-muted-foreground">{data.uploads.length} videos sin editado entregado · {data.today.filter(i=>i.missing).length} clientes sin pieza fechada</p></div><span className="rounded-full bg-primary/10 px-3 py-1.5 text-xs font-medium text-primary">{data.today.filter(i=>i.done).length} / {data.today.length} Publicados</span></div><p className="mb-4 text-xs text-muted-foreground">Se completa con el estado del trabajo. Enviar a Metricool todavía requiere verificar la publicación.</p>{data.today.length?<><ul className="grid gap-3 lg:grid-cols-2">{data.today.slice(0,8).map(i=><TaskRow key={i.id} item={i}/>)}</ul>{data.today.length>8&&<details className="mt-3"><summary className="cursor-pointer py-3 text-sm font-medium text-primary">Ver Los {data.today.length-8} Compromisos Restantes De Hoy</summary><ul className="grid gap-3 lg:grid-cols-2">{data.today.slice(8).map(i=><TaskRow key={i.id} item={i}/>)}</ul></details>}</>:<p className="py-5 text-sm text-muted-foreground">No hay videos fechados ni compromisos de calendario para hoy.</p>}</section>
  <section id="editores" className="scroll-mt-24 rounded-xl border bg-card p-4 sm:p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Espacios De Edición</h2><p className="mt-1 text-xs text-muted-foreground">Capacidad actual del banco de edición; el tope sube según el historial de aprobación.</p></div><Link href="/pipeline" className="inline-flex min-h-11 items-center gap-2 text-sm font-medium text-primary">Llenar Espacios <ArrowUpRight className="h-4 w-4"/></Link></div><ul className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data.editors.map(e=><li key={e.id} className="rounded-lg border p-4"><div className="flex items-center justify-between gap-3"><p className="min-w-0 break-words text-sm font-semibold">{e.name}</p><span className="shrink-0 text-xs text-muted-foreground">{e.used} / {e.limit}</span></div><div className="my-3 flex gap-1.5" aria-hidden>{Array.from({length:e.limit},(_,i)=><span key={i} className={`h-2 flex-1 rounded-full ${i<e.used?'bg-primary':'bg-muted'}`}/>)}</div><p className={`text-xs ${e.free?'text-primary':'text-muted-foreground'}`}>{e.free?`${e.free} espacios por llenar`:'Espacios completos'}</p></li>)}</ul>{!data.editors.length&&<p className="text-sm text-muted-foreground">No hay editores activos.</p>}</section>
  <p className="text-xs text-muted-foreground">Las siguientes colas incluyen trabajo de todas las fechas. Los atrasos se muestran por separado del checklist de hoy.</p>
  <div className="grid items-start gap-4 xl:grid-cols-2"><Queue id="revisiones" title="Por Revisar" items={data.reviews} href="/revision" empty="No hay entregas pendientes de revisión."/><Queue id="agendar" title="Por Agendar En Metricool" items={data.ready} href="/entregas" empty="No hay videos listos para agendar. Revisa los bloqueos pendientes."/></div>
  <details className="rounded-xl border p-4"><summary className="cursor-pointer py-2 font-semibold">Bloqueos Para Agendar ({data.blocked.length}) · Correcciones ({data.corrections.length}) · Atrasados ({data.overdue.length})</summary><div className="mt-4 space-y-4"><Queue id="bloqueos" title="Completar Antes De Agendar" items={data.blocked} href="/entregas" empty="Sin bloqueos."/><Queue id="correcciones" title="Devolver Al Editor" items={data.corrections} href="/revision" empty="Sin correcciones pendientes."/><Queue id="atrasados" title="Atrasos · No Son Trabajo De Hoy" items={data.overdue} href="/produccion" empty="Sin atrasos."/></div></details>
 </div>
}
