'use client'
import {useEffect,useState} from 'react'
import {auditOperationalPublications} from '@/lib/actions/operational-publications'
import type {OperationalPublicationReport} from '@/lib/utils/operational-publications'
const labels:Record<string,string>={published:'Publicado',scheduled:'Programado',draft:'Borrador',partial:'Publicación Parcial',failed:'Falló',unknown:'Sin Verificar',unverified:'Sin Coincidencia En Metricool'}
export function PublicationChecklist(){
 const [report,setReport]=useState<OperationalPublicationReport|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('')
 async function check(){setLoading(true);setError('');setReport(null);try{const r=await auditOperationalPublications();setReport(r.report??null);setError(r.error??'')}catch{setError('No se pudo verificar Metricool.')}finally{setLoading(false)}}
 useEffect(()=>{void check();const timer=setInterval(()=>{if(document.visibilityState==='visible')void check()},300000);return()=>clearInterval(timer)},[])
 const verified=report?.clients.filter(c=>!c.error)??[]
 return <section className="rounded-xl border border-sky-500/25 bg-card p-4 sm:p-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Publicación Real Y Cobertura Futura</h2><p className="mt-1 text-xs text-muted-foreground">Últimos 7 días, hoy y próximos 14 días · Puerto Rico · Verificación por red.</p></div><button onClick={check} disabled={loading} className="min-h-11 rounded-lg bg-sky-600 px-4 text-sm font-medium text-white disabled:opacity-50">{loading?'Consultando Metricool…':'Verificar Ahora'}</button></div>
  {error&&<p role="alert" className="mt-3 text-sm text-rose-500">{error}</p>}
  {report&&<div className="mt-4 space-y-3"><p className="text-xs text-muted-foreground">Última Consulta: {new Date(report.checkedAt).toLocaleString('es-PR',{timeZone:'America/Puerto_Rico'})}. Los estados no consultados no se cuentan como completados.</p><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[
   ['Fechas Vencidas Sin Confirmar',verified.reduce((n,c)=>n+c.overdue,0)],['Clientes Sin Verificar',report.clients.length-verified.length],['Días Futuros Cubiertos',verified.reduce((n,c)=>n+c.futureCovered,0)],['Días Futuros Por Cubrir',verified.reduce((n,c)=>n+c.futureRequired-c.futureCovered,0)],
  ].map(([label,count])=><div key={label} className="rounded-lg border p-3"><p className="text-2xl font-semibold">{count}</p><p className="text-xs text-muted-foreground">{label}</p></div>)}</div>
  <p className="text-xs text-muted-foreground">Cada día se cuenta por cliente. La cobertura exige la pieza fechada vinculada a Metricool; un borrador no cubre la fecha.</p>
  <div className="space-y-2">{report.clients.map(c=><details key={c.id} className="rounded-lg border p-3"><summary className="cursor-pointer text-sm font-medium">{c.name} · {c.error??`${c.futureCovered}/${c.futureRequired} días futuros cubiertos · ${c.overdue} vencidos sin confirmar`}{!c.error&&c.nextGap?` · Primer Hueco: ${c.nextGap}`:''}</summary>{!c.error&&<ul className="mt-3 space-y-3">{c.days.map(d=><li key={d.date} className="rounded-md border p-3 text-xs"><p className="font-semibold">{d.date===report.today?'HOY · ':''}{d.date} · {d.covered?'Cubierto':d.date<report.today?'Vencido · Sin Confirmación':d.date===report.today?'Pendiente De Publicar':'Por Cubrir'} · {d.published} publicados / {d.expected} previstos</p>{d.videos.map(v=><div key={v.id} className="mt-2"><a href={`/produccion/idea/${v.id}`} className="underline">{v.title}</a> · {labels[v.state]}{v.networks.map((n,i)=><p key={i}>{n.network}: {n.status}{n.publicUrl&&/^https:\/\//.test(n.publicUrl)&&<> · <a href={n.publicUrl} target="_blank" rel="noreferrer" className="underline">Ver Publicación</a></>}</p>)}</div>)}{!d.videos.length&&d.posts.map(p=><p key={p.id} className="mt-2">Metricool #{p.id} · {labels[p.state]} · {p.networks.map(n=>`${n.network}: ${n.status}`).join(' · ')}</p>)}{!d.videos.length&&!d.posts.length&&<p className="mt-2 text-amber-500">Sin Pieza Fechada Ni Publicación En Metricool</p>}</li>)}</ul>}</details>)}</div></div>}
 </section>
}
