'use client'
import {saveClientEditorTeam} from '@/lib/actions/client-editor-team'
import {useRouter} from 'next/navigation'
import {useEffect,useState} from 'react'
import {getRecordingEditorSetup,saveRecordingEditors,type EditorSetup} from '@/lib/actions/recording-editors'
export function RecordingEditors({sessionId,onSaved}:{sessionId?:string;onSaved:()=>void}){
 const router=useRouter()
 const [data,setData]=useState<EditorSetup|null>(null),[client,setClient]=useState(''),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{let active=true;getRecordingEditorSetup(sessionId).then(r=>{if(!active)return;setData(r);const id=r.clientId||'';setClient(id);setSelected([...new Set([r.clients.find(c=>c.id===id)?.assigned_to,...r.links.filter(l=>l.client_id===id).map(l=>l.editor_id)].filter((v):v is string=>!!v))])}).catch(()=>{if(active)setError('No Se Pudo Cargar La Asignación')});return()=>{active=false}},[sessionId])
 async function save(){setBusy(true);setError('');try{const r=sessionId?await saveRecordingEditors(sessionId,client,selected):await saveClientEditorTeam(client,selected);if(r.error)setError(r.error);else if(r.ok){setData(current=>current?{...current,links:[...current.links.filter(l=>l.client_id!==client),...selected.map(editor_id=>({client_id:client,editor_id}))],clients:current.clients.map(c=>c.id===client?{...c,assigned_to:c.assigned_to&&selected.includes(c.assigned_to)?c.assigned_to:[...selected].sort()[0]}:c)}:current);router.refresh();window.dispatchEvent(new Event('recording-preparation-changed'));onSaved()}}catch{setError('No Se Pudo Confirmar El Guardado. Reabre La Asignación Para Verificar Antes De Cambiarla.')}finally{setBusy(false)}}
 if(!data)return <p>{error||'Cargando Editores…'}</p>
 if(data.error)return <p role="alert" className="rounded-lg border border-amber-500/30 p-3 text-sm">{data.error}</p>
 return <div className="space-y-4"><p className="text-sm text-muted-foreground">Cada editor seleccionado quedará vinculado a este cliente y lo verá en su perfil. Esta asignación se comparte entre sus grabaciones.</p><label className="block text-sm">Cliente<select value={client} disabled={!!data.clientId||busy} onChange={e=>{const id=e.target.value;setClient(id);setSelected([...new Set([data.clients.find(c=>c.id===id)?.assigned_to,...data.links.filter(l=>l.client_id===id).map(l=>l.editor_id)].filter((v):v is string=>!!v))])}} className="mt-1 w-full rounded-lg border bg-background p-2"><option value="">Selecciona El Cliente</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><fieldset disabled={!client||busy} className="max-h-64 space-y-2 overflow-y-auto"><legend className="mb-2 text-sm font-medium">Editores · Selecciona Uno O Varios</legend>{data.editors.map(p=><label key={p.id} className="flex items-center gap-3 rounded-lg border p-3 text-sm"><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(current=>e.target.checked?[...current,p.id]:current.filter(id=>id!==p.id))}/>{p.full_name||'Sin Nombre'}</label>)}</fieldset>{error&&<p role="alert" className="text-sm text-red-500">{error}</p>}<button onClick={save} disabled={!client||!selected.length||busy} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50">{busy?'Guardando…':'Guardar Editores'}</button></div>
}
